# Generated by Django 4.1.7 on 2023-11-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GQL_API", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
