# Generated by Django 4.1.7 on 2023-10-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrainInstanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brain_type", models.CharField(default="trained", max_length=100)),
                ("brain_id", models.CharField(max_length=350)),
                ("generation_num", models.CharField(max_length=350)),
                ("fitness", models.CharField(max_length=350)),
                ("hidden_weights", models.BinaryField()),
                ("output_weights", models.BinaryField()),
            ],
        ),
    ]
