# Generated by Django 4.1.7 on 2023-10-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braininstancemodel",
            name="hidden_weights",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="output_weights",
            field=models.CharField(max_length=350),
        ),
    ]
