# Generated by Django 4.1.7 on 2023-10-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_braininstancemodel_hidden_weights_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braininstancemodel",
            name="hidden_weights",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="output_weights",
            field=models.BinaryField(),
        ),
    ]
