# Generated by Django 4.1.7 on 2023-10-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_braininstancemodel_hidden_weights_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="braininstancemodel",
            old_name="generation_num",
            new_name="current_generation_number",
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="fitness_by_step",
            field=models.CharField(default="[]", max_length=350),
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="traversed_path",
            field=models.CharField(default="[]", max_length=350),
        ),
    ]
