# Generated by Django 4.1.7 on 2023-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database",
            "0004_rename_generation_num_braininstancemodel_current_generation_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="braininstancemodel",
            name="hidden_layer_activation_func",
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="new_generation_func",
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="output_layer_activation_func",
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
