# Generated by Django 4.1.7 on 2023-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_braininstancemodel_hidden_layer_activation_func_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="hidden_layer_activation_func",
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="new_generation_func",
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="output_layer_activation_func",
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="function_ref",
            field=models.CharField(default={}, max_length=350),
        ),
    ]
