# Generated by Django 4.1.7 on 2023-10-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0006_remove_braininstancemodel_hidden_layer_activation_func_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="function_ref",
        ),
    ]
