# Generated by Django 4.1.7 on 2023-10-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_remove_braininstancemodel_function_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="braininstancemodel",
            name="function_ref",
            field=models.CharField(default={}, max_length=350),
        ),
    ]
