# Generated by Django 4.1.7 on 2023-10-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_braininstancemodel_function_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="braininstancemodel",
            old_name="function_ref",
            new_name="functions_ref",
        ),
    ]
