# Generated by Django 4.1.7 on 2023-10-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_rename_function_ref_braininstancemodel_functions_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="hidden_weights",
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="output_weights",
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="functions_callabe",
            field=models.CharField(default={}, max_length=350),
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="weights",
            field=models.JSONField(default={}),
        ),
    ]
