# Generated by Django 4.1.7 on 2023-10-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_alter_braininstancemodel_functions_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="braininstancemodel",
            old_name="functions_callabe",
            new_name="functions_callable",
        ),
    ]
