# Generated by Django 4.1.7 on 2023-10-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0012_rename_functions_callabe_braininstancemodel_functions_callable",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="braininstancemodel",
            name="functions_callable",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="functions_ref",
            field=models.JSONField(default={}),
        ),
    ]
