# Generated by Django 4.1.7 on 2023-10-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0013_alter_braininstancemodel_functions_callable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braininstancemodel",
            name="functions_callable",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="functions_ref",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="weights",
            field=models.JSONField(default=dict),
        ),
    ]
