# Generated by Django 4.1.7 on 2023-10-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_alter_braininstancemodel_functions_callable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationInstanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generation_id", models.CharField(max_length=350)),
                ("generation_number", models.CharField(max_length=350)),
                ("average_fitness", models.CharField(max_length=350)),
                ("fitness_threshold", models.CharField(max_length=350)),
                ("generation_brain_instances", models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="functions_ref",
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="fitness_by_step",
            field=models.CharField(default=list, max_length=350),
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="traversed_path",
            field=models.CharField(default=list, max_length=350),
        ),
    ]
