# Generated by Django 4.1.7 on 2023-10-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0016_learninginstancemodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learninginstancemodel",
            old_name="instance_id",
            new_name="learning_instance_id",
        ),
    ]
