# Generated by Django 4.1.7 on 2023-10-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0018_generationinstancemodel_generation_alpha_brain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationinstancemodel",
            old_name="generation_id",
            new_name="generation_instance_id",
        ),
        migrations.AlterField(
            model_name="braininstancemodel",
            name="generation_instance_ref",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_ref",
                to="database.generationinstancemodel",
            ),
        ),
        migrations.AlterField(
            model_name="generationinstancemodel",
            name="learning_instance_ref",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_ref",
                to="database.learninginstancemodel",
            ),
        ),
    ]
