# Generated by Django 4.1.7 on 2023-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0019_rename_generation_id_generationinstancemodel_generation_instance_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generationinstancemodel",
            name="generation_size",
            field=models.CharField(default=0, max_length=350),
        ),
    ]
