# Generated by Django 4.1.7 on 2023-11-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0020_generationinstancemodel_generation_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="braininstancemodel",
            name="svg_end",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="svg_path",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="braininstancemodel",
            name="svg_start",
            field=models.CharField(default="", max_length=350),
        ),
    ]
