# Generated by Django 4.1.7 on 2023-11-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0021_braininstancemodel_svg_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="svg_end",
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="svg_path",
        ),
        migrations.RemoveField(
            model_name="braininstancemodel",
            name="svg_start",
        ),
    ]
